name: First Shell commands

on:
  push:

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a String
        run: echo "Hello Midde"
      - name: Multi Line Shell
        run: |
          node -v
          npm -v